url: "woodwyynn.ktts.me" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "woodwyynn" # the name of your site, e.g. ACME Corp.
subtitle: "i am not a fruit"
description: "a candid, cozy, cabbalistic, and cabbagy centre for curious connoisseurs."
license: "MIT"

author: "kanen stephens"

insta: "https://instagram.com/woodwyynn"
repo: "https://github.com/kanennn/woodwyynn"

collections:
    posts:
        output: true
        permalink: /stories/:title

exclude:
    - README.md
plugins:
    - jekyll-coffeescript
